packages:
  - desktop
  - server
  - packages/*
  - '!packages/remote-relay'
  - electron
allowBuilds:
  '@google/genai': set this to true or false
  better-sqlite3: set this to true or false
  electron: set this to true or false
  esbuild: set this to true or false
  node-pty: set this to true or false
  protobufjs: set this to true or false
