import type { TailscaleRemoteRuntimeState } from "@/shared/api/generalSettings";

const zh = {
  page: {
    miniTitle: "REMOTE ACCESS",
    title: "远程连接",
    description: "",
  },
  relay: {
    title: "Mira Relay",
    default: "默认服务",
    custom: "自定义地址",
    customAddress: "Relay 地址",
    customPlaceholder: "https://relay.example.com",
    states: {
      disabled: "未启用",
      misconfigured: "配置异常",
      connecting: "连接中",
      connected: "已连接",
      disconnected: "已断开",
      stopped: "已停止",
      unavailable: "不可用",
    },
    messages: {
      loadFailed: "加载 Mira Relay 状态失败",
      saveFailed: "保存 Mira Relay 设置失败",
    },
  },
  status: {
    title: "连接状态",
    connection: "Tailscale 连接",
    enable: "启用 Tailscale",
    enableDescription: "保存后由 Mira 安全配置 Tailscale Serve，不开放公网端口。",
    states: {
      not_installed: ["未安装", "没有找到 Tailscale CLI。"],
      needs_login: ["待登录", "请先让这台电脑加入 Tailnet。"],
      connecting: ["连接中", "Tailscale 正在建立连接。"],
      connected: ["已连接", "Tailnet 已就绪，远程入口尚未启用。"],
      serve_conflict: ["配置冲突", "检测到其他 Serve 配置，Mira 没有覆盖它。"],
      serve_not_configured: ["待发布", "设置要求启用，但 Mira Serve 尚未生效。"],
      unreachable: ["不可访问", "Serve 已配置，但远程健康检查没有通过。"],
      ready: ["可访问", "Tailnet、Serve 与 Mira 健康检查均正常。"],
      error: ["检查失败", "读取 Tailscale 运行状态失败。"],
    } satisfies Record<TailscaleRemoteRuntimeState, readonly [string, string]>,
  },
  device: {
    title: "设备配置",
    name: "设备名称",
    tailnet: "Tailnet 域名",
    accessAddress: "访问地址",
    unavailable: "等待 Tailscale 提供",
    open: "打开地址",
  },
  devices: {
    title: "已配对设备",
    empty: "暂无已配对设备",
    emptyHint: "",
    lastSeen: "最近连接",
    neverSeen: "尚未连接",
    revoke: "撤销",
    revoked: "设备已撤销",
    revokeFailed: "撤销设备失败",
  },
  diagnostics: {
    title: "诊断信息",
    version: "Tailscale 版本",
    backend: "Backend 状态",
    ips: "Tailscale IP",
    serve: "Mira Serve",
    serveManaged: "已配置并由 Mira 管理",
    serveMissing: "未配置",
    serveOther: "存在其他配置",
    health: "远程健康检查",
    healthOk: "通过",
    healthFailed: "未通过",
    healthPending: "尚未执行",
    checkedAt: "检查时间",
  },
  actions: {
    help: "Tailscale 帮助",
    diagnose: "诊断",
    checking: "检查中...",
    saving: "保存中...",
  },
  messages: {
    loadFailed: "加载 Tailscale 状态失败",
    checkFailed: "检查 Tailscale 连接失败",
    saved: "Tailscale 设置已保存",
    saveFailed: "保存 Tailscale 设置失败",
  },
  guide: {
    title: "Tailscale 远程连接",
    intro: "Mira 只发布本机 Host 到私有 Tailnet，不启用 Funnel，也不会覆盖已有的其他 Serve 配置。",
    close: "关闭帮助说明",
    steps: [
      ["安装并登录 Tailscale", "电脑与手机需要加入同一个受信 Tailnet。"],
      ["让 Mira 检查运行状态", "设备名、MagicDNS 与 IP 都由 CLI 自动读取。"],
      ["保存并启用远程入口", "Mira 先检查 Serve 冲突，再发布 localhost Host，并验证 /health。"],
      ["继续使用 Mira 认证", "进入 Tailnet 只解决网络可达，不会绕过账号、设备凭证或工具审批。"],
    ] as const,
  },
};

const en = {
  page: {
    miniTitle: "REMOTE ACCESS",
    title: "Remote Access",
    description: "",
  },
  relay: {
    title: "Mira Relay",
    default: "Default service",
    custom: "Custom address",
    customAddress: "Relay address",
    customPlaceholder: "https://relay.example.com",
    states: {
      disabled: "Off",
      misconfigured: "Invalid",
      connecting: "Connecting",
      connected: "Connected",
      disconnected: "Disconnected",
      stopped: "Stopped",
      unavailable: "Unavailable",
    },
    messages: {
      loadFailed: "Failed to load Mira Relay status",
      saveFailed: "Failed to save Mira Relay settings",
    },
  },
  status: {
    title: "Connection status",
    connection: "Tailscale connection",
    enable: "Enable Tailscale",
    enableDescription: "After saving, Mira configures Tailscale Serve without opening a public port.",
    states: {
      not_installed: ["Not installed", "The Tailscale CLI was not found."],
      needs_login: ["Sign-in required", "Join this computer to a Tailnet first."],
      connecting: ["Connecting", "Tailscale is establishing the connection."],
      connected: ["Connected", "The Tailnet is ready and the Mira endpoint is disabled."],
      serve_conflict: ["Serve conflict", "Another Serve configuration exists and Mira did not overwrite it."],
      serve_not_configured: ["Publish required", "Remote access is enabled in settings but Mira Serve is not active."],
      unreachable: ["Unreachable", "Serve is configured, but the remote health check failed."],
      ready: ["Ready", "Tailnet, Serve, and the Mira health check are all working."],
      error: ["Check failed", "Mira could not read the Tailscale runtime state."],
    } satisfies Record<TailscaleRemoteRuntimeState, readonly [string, string]>,
  },
  device: {
    title: "Device configuration",
    name: "Device name",
    tailnet: "Tailnet domain",
    accessAddress: "Access address",
    unavailable: "Waiting for Tailscale",
    open: "Open address",
  },
  devices: {
    title: "Paired devices",
    empty: "No paired devices",
    emptyHint: "",
    lastSeen: "Last seen",
    neverSeen: "Never connected",
    revoke: "Revoke",
    revoked: "Device revoked",
    revokeFailed: "Failed to revoke device",
  },
  diagnostics: {
    title: "Diagnostics",
    version: "Tailscale version",
    backend: "Backend state",
    ips: "Tailscale IP",
    serve: "Mira Serve",
    serveManaged: "Configured and managed by Mira",
    serveMissing: "Not configured",
    serveOther: "Another configuration exists",
    health: "Remote health check",
    healthOk: "Passed",
    healthFailed: "Failed",
    healthPending: "Not run",
    checkedAt: "Checked at",
  },
  actions: {
    help: "Tailscale Help",
    diagnose: "Diagnose",
    checking: "Checking...",
    saving: "Saving...",
  },
  messages: {
    loadFailed: "Failed to load Tailscale status",
    checkFailed: "Failed to check Tailscale",
    saved: "Tailscale settings saved",
    saveFailed: "Failed to save Tailscale settings",
  },
  guide: {
    title: "Tailscale remote access",
    intro: "Mira publishes only the local Host to a private Tailnet. It never enables Funnel or overwrites another Serve configuration.",
    close: "Close help",
    steps: [
      ["Install and sign in to Tailscale", "The computer and phone must join the same trusted Tailnet."],
      ["Let Mira inspect the runtime", "The device name, MagicDNS name, and IP come directly from the CLI."],
      ["Save and enable the endpoint", "Mira checks for Serve conflicts, publishes the localhost Host, then verifies /health."],
      ["Keep Mira authentication enabled", "Tailnet reachability never bypasses account, device, or tool-approval checks."],
    ] as const,
  },
};

export const getTailscaleRemoteAccessCopy = (language?: string) =>
  language?.toLowerCase().startsWith("zh") ? zh : en;
